import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {getV11AiContract,buildV11AiGenerationPrompt,validateV11AiOutput} from '../js/engines/v11-ai-generation-contract.js';
import {decideV11Publication} from '../js/engines/v11-publication-gate.js';
import {diagnoseV11ChoiceResponse,updateV11MisconceptionProfile} from '../js/engines/v11-misconception-profile.js';
import {attachV11SilentRemediation} from '../js/engines/v11-misconception-remediation.js';
import {buildV11MisconceptionDevelopmentReport} from '../js/engines/v11-misconception-report.js';
import {composeV11Session} from '../js/engines/v11-session-composer.js';
const catalog=JSON.parse(fs.readFileSync(new URL('../content/v11/ai-generation-contracts.v11.json',import.meta.url),'utf8'));
const c=getV11AiContract(catalog,'INFO_SECME_01');
function output(){return {contractId:c.contractId,skeletonId:c.skeletonId,difficulty:2,variationAxis:c.generationInstruction.variationAxes[0],source:'Arılar, yiyecek kaynağının yönünü ve uzaklığını kovandaki diğer arılara özel dans hareketleriyle aktarır.',prompt:'Metne göre arılar yön bilgisini nasıl paylaşır?',options:['Özel dans hareketleriyle paylaşır.','Kovana farklı bir koku bırakarak paylaşır.','Vücut rengini değiştirerek paylaşır.','Kanat sesini tamamen keserek paylaşır.'],correctIndex:0,explanation:'E1 kanıtı, yön bilgisinin özel dans hareketleriyle aktarıldığını açıkça belirtir.',evidenceMap:{evidenceUnits:[{evidenceId:'E1',text:'yönünü ve uzaklığını özel dans hareketleriyle aktarır'}],correctAnswerEvidenceIds:['E1']},optionDiagnostics:[{optionIndex:0,isCorrect:true,misconceptionId:null,evidenceIds:['E1']},{optionIndex:1,isCorrect:false,misconceptionId:'INFO_SECME_01_M1',misconception:'Metin dışı ayrıntı',evidenceIds:[]},{optionIndex:2,isCorrect:false,misconceptionId:'INFO_SECME_01_M2',misconception:'Yüzeysel çağrışım',evidenceIds:[]},{optionIndex:3,isCorrect:false,misconceptionId:'INFO_SECME_01_M3',misconception:'İlgisiz ayrıntı',evidenceIds:[]}],qualitySelfCheck:{oneBestAnswer:true,noAnswerLeak:true,skeletonLogicPreserved:true,distinctMisconceptions:true,realVariationUsed:true}};}

test('iskelet sözleşmesinden çalıştırılabilir AI promptu ve geçerli aday soru üretilir',()=>{const prompt=buildV11AiGenerationPrompt(c,{difficulty:2});assert.match(prompt,/INFO_SECME_01/);assert.equal(validateV11AiOutput(output(),c).accepted,true);});
test('geçerli aday yalnız yayın kapısından PUBLISH olarak geçer',()=>{const result=decideV11Publication({output:output(),catalog});assert.equal(result.decision,'PUBLISH');assert.equal(result.auditTrail.studentVisible,true);});
test('oynanabilir turdaki yanlış seçenek tanısı kalıcı profile yazılır',()=>{const round={...output(),skeletonFamilyId:'INFO_SECME',questionKey:'q1',questionFamilyId:'f1'};const diagnosis=diagnoseV11ChoiceResponse(round,1,false);const state={};updateV11MisconceptionProfile(state,{profileId:'p1',correct:false,questionKey:'q1',questionFamilyId:'f1',...diagnosis});assert.equal(diagnosis.diagnosticStatus,'MISCONCEPTION_CAPTURED');assert.equal(state.misconceptionProfiles.p1.totalDiagnosedErrors,1);});
test('tekrar eden yanılgı sessiz telafi ve V11 oturum bestecisine bağlanır',()=>{const round={...output(),skeletonFamilyId:'INFO_SECME',questionKey:'q1',questionFamilyId:'f1'};const diagnosis=diagnoseV11ChoiceResponse(round,1,false);const attempts=[{correct:false,questionKey:'q1',questionFamilyId:'f1',...diagnosis},{correct:false,questionKey:'q2',questionFamilyId:'f1',...diagnosis}];const rem=attachV11SilentRemediation([round,{...round,questionKey:'q3'}],attempts);const session=composeV11Session(rem.rounds,{targetCount:2,misconceptionInterventions:rem.interventions});assert.equal(rem.audit.attachedRoundCount,1);assert.equal(session.audit.forbiddenViolationCount,0);assert.ok(session.audit.remediationCount<=session.audit.remediationLimit);});
test('tanılanmış tekrar öğretmen ve veli gelişim raporuna dönüşür',()=>{const round={...output(),skeletonFamilyId:'INFO_SECME',questionKey:'q1',questionFamilyId:'f1'};const d=diagnoseV11ChoiceResponse(round,1,false);const report=buildV11MisconceptionDevelopmentReport([{correct:false,questionKey:'q1',...d},{correct:false,questionKey:'q2',...d}],{windowSize:4});assert.equal(report.status,'READY');assert.equal(report.distinctMisconceptionCount,1);assert.equal(report.diagnosedErrorCount,2);});
