import test from 'node:test';import assert from 'node:assert/strict';
import {defineHumanReviewDecision,auditHumanReviewDecisions} from '../../js/assessment-v2/human-review-decision-contract.js';
import {buildHumanReviewConsensus,requiredReviewerCount} from '../../js/assessment-v2/human-review-consensus.js';
import {ASSESSMENT_V2_RISK_REVIEW_SAMPLE} from '../../js/assessment-v2/risk-stratified-review-sampler.js';
const scores={correctness:5,optionOrRubricQuality:4,ageLanguageFit:4,hintNonLeakage:5,feedbackTeachingValue:4,naturalness:4};
function decision(questionId,reviewerAnonId,decisionValue='APPROVE',override={}){return defineHumanReviewDecision({reviewId:`r_${questionId}_${reviewerAnonId}`,batchId:'PHASE4P_70',questionId,reviewerAnonId,reviewerRole:'CONTENT_REVIEWER',decision:decisionValue,scores:{...scores,...override.scores},criticalBlockers:override.criticalBlockers||[],notes:'Kalibrasyon notu',reviewedAt:'2026-08-04T09:00:00.000Z'});}
test('insan inceleme sözleşmesi PII ve düşük puanla APPROVE kararını reddeder',()=>{assert.throws(()=>defineHumanReviewDecision({name:'Ali'}),/pii-forbidden/);const q=ASSESSMENT_V2_RISK_REVIEW_SAMPLE.rows[0].questionId;assert.throws(()=>decision(q,'reviewer_test01','APPROVE',{scores:{correctness:3}}),/threshold/);});
test('70 görevlik örneklemde yüksek karmaşıklık çift, düşük karmaşıklık tek inceleme ister',()=>{assert.equal(ASSESSMENT_V2_RISK_REVIEW_SAMPLE.rows.length,70);assert.ok(ASSESSMENT_V2_RISK_REVIEW_SAMPLE.rows.some(r=>requiredReviewerCount(r)===2));assert.ok(ASSESSMENT_V2_RISK_REVIEW_SAMPLE.rows.some(r=>requiredReviewerCount(r)===1));});
test('tek incelemeli görev uygun puanlarla APPROVED olur',()=>{const row=ASSESSMENT_V2_RISK_REVIEW_SAMPLE.rows.find(r=>requiredReviewerCount(r)===1);const result=buildHumanReviewConsensus({queueRows:[row],decisions:[decision(row.questionId,'reviewer_alpha01')]});assert.equal(result.rows[0].status,'APPROVED');assert.equal(result.rows[0].gameAdaptationAllowed,true);assert.equal(result.rows[0].publicationAllowed,false);});
test('yüksek riskli görev tek uzmanla açılmaz, ikinci bağımsız onayla açılır',()=>{const row=ASSESSMENT_V2_RISK_REVIEW_SAMPLE.rows.find(r=>requiredReviewerCount(r)===2);const one=buildHumanReviewConsensus({queueRows:[row],decisions:[decision(row.questionId,'reviewer_alpha01')]});assert.equal(one.rows[0].status,'MORE_REVIEWS_REQUIRED');const two=buildHumanReviewConsensus({queueRows:[row],decisions:[decision(row.questionId,'reviewer_alpha01'),decision(row.questionId,'reviewer_beta01')]});assert.equal(two.rows[0].status,'APPROVED');});
test('REVISE veya REJECT kararı onay çoğunluğuyla gizlenemez',()=>{const row=ASSESSMENT_V2_RISK_REVIEW_SAMPLE.rows.find(r=>requiredReviewerCount(r)===2);const revise=defineHumanReviewDecision({reviewId:'revise1',batchId:'PHASE4P_70',questionId:row.questionId,reviewerAnonId:'reviewer_beta01',reviewerRole:'CONTENT_REVIEWER',decision:'REVISE',scores:{...scores,optionOrRubricQuality:3},criticalBlockers:[],notes:'Çeldirici revizyonu',reviewedAt:'2026-08-04T09:00:00.000Z'});const result=buildHumanReviewConsensus({queueRows:[row],decisions:[decision(row.questionId,'reviewer_alpha01'),revise]});assert.equal(result.rows[0].status,'REVISION_REQUIRED');});
test('aynı uzmanın aynı göreve iki karar vermesi veri denetiminde RED olur',()=>{const row=ASSESSMENT_V2_RISK_REVIEW_SAMPLE.rows[0];const d=decision(row.questionId,'reviewer_alpha01');const copy={...d,reviewId:'other'};const audit=auditHumanReviewDecisions([d,copy]);assert.equal(audit.ok,false);assert.ok(audit.errors.includes('duplicate-reviewer-question'));});
