import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { GRADE5_COMPUTING_OUTCOMES_TYMM_2024 } from '../../js/curriculum/outcomes/tr-g5-bilisim-teknolojileri-ve-yazilim-tymm-2024.js';
import { GRADE6_COMPUTING_OUTCOMES_TYMM_2024 } from '../../js/curriculum/outcomes/tr-g6-bilisim-teknolojileri-ve-yazilim-tymm-2024.js';
import { PRIMARY_TYMM_SOURCE_EVIDENCE } from '../../js/curriculum/primary-tymm-source-evidence.js';
import { COURSE_SCHEDULE_REGISTRY_2026_2027 } from '../../js/curriculum/course-schedule-registry-2026-2027.js';
import { MIDDLE_SCHOOL_TYMM_COMPUTING_AUDIT, MIDDLE_SCHOOL_TYMM_COMPUTING_ENGINE_RECORDS, buildMiddleSchoolTymmComputingTasks } from '../../js/assessment-v2/middle-school-tymm-computing-engines.js';
import { MIDDLE_SCHOOL_TYMM_COMPUTING_REVIEW_SAMPLE_AUDIT } from '../../js/assessment-v2/middle-school-tymm-computing-review-sample.js';
import { ASSESSMENT_V2_PRODUCTION_PORTFOLIO, ASSESSMENT_V2_PRODUCTION_PORTFOLIO_AUDIT } from '../../js/assessment-v2/production-portfolio.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const sets=[GRADE5_COMPUTING_OUTCOMES_TYMM_2024,GRADE6_COMPUTING_OUTCOMES_TYMM_2024];const all=sets.flat();

test('5-6. sınıf Bilişim programı 24 ve 25 resmî çıktı taşır',()=>{assert.deepEqual(sets.map(rows=>rows.length),[24,25]);assert.equal(all.length,49);assert.equal(new Set(all.map(row=>`${row.grade}:${row.officialOutcomeCode}`)).size,49);});
test('resmî Bilişim PDF kanıtı yerel SHA-256 ve aktif TYMM yönlendirmesiyle doğrulanır',()=>{const evidence=PRIMARY_TYMM_SOURCE_EVIDENCE.find(row=>row.sourceId==='meb-tymm-bilisim-5-6-2024');assert.ok(evidence);assert.deepEqual(evidence.grades,[5,6]);const file=path.join(root,evidence.localDocument);assert.equal(fs.existsSync(file),true);assert.equal(crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),evidence.sha256);assert.equal(evidence.status,'LOCAL_AUTHORITATIVE_EVIDENCE_VERIFIED');});
test('Bilişim çıktıları ayrıştırma artığı, kesik cümle ve yinelenen kod içermez',()=>{const forbidden=/ÖĞRENME ÇIKTILARI|SÜREÇ BİLEŞENLERİ|ÖĞRENME KANITLARI|FARKLILAŞTIRMA|^[a-zçğıöşü]\)|\s{3,}/i;assert.equal(all.every(row=>row.programFamily==='TYMM'&&[5,6].includes(row.grade)&&row.courseId==='bilisim-teknolojileri-ve-yazilim'),true);assert.equal(all.some(row=>forbidden.test(row.officialOutcomeText)),false);assert.equal(all.every(row=>row.officialOutcomeText.length>=24&&row.sourceLocator.includes(`${row.grade}. sınıf`)),true);});
test('iki ayrı Bilişim motoru 49 görevi güvenli sandbox, rubrik ve bağımsız doğrulamayla üretir',()=>{const tasks=buildMiddleSchoolTymmComputingTasks();assert.equal(MIDDLE_SCHOOL_TYMM_COMPUTING_AUDIT.ok,true);assert.equal(MIDDLE_SCHOOL_TYMM_COMPUTING_ENGINE_RECORDS.length,2);assert.equal(tasks.length,49);assert.equal(tasks.every(item=>item.hints.length===3&&item.misconceptionIds.length>=3&&item.content.media.status==='SAFE_OFFLINE_OR_SCHOOL_MANAGED_DIGITAL_SANDBOX_REQUIRED'&&item.responseModel.personalDataProhibited===true&&item.gameBindings.length===0),true);});
test('Bilişim hücreleri ders çizelgesine bağlı ve ürün sayaçları günceldir',()=>{const cells=new Set(COURSE_SCHEDULE_REGISTRY_2026_2027.map(row=>`${row.grade}:${row.courseId}`));assert.equal(MIDDLE_SCHOOL_TYMM_COMPUTING_ENGINE_RECORDS.every(record=>cells.has(`${record.grade}:bilisim-teknolojileri-ve-yazilim`)),true);assert.equal(ASSESSMENT_V2_PRODUCTION_PORTFOLIO_AUDIT.ok,true,ASSESSMENT_V2_PRODUCTION_PORTFOLIO_AUDIT.errors.join('\n'));assert.equal(ASSESSMENT_V2_PRODUCTION_PORTFOLIO.summary.activeEngineCellCount,59);assert.equal(ASSESSMENT_V2_PRODUCTION_PORTFOLIO.summary.curriculumOutcomeRecordCount,2350);assert.equal(ASSESSMENT_V2_PRODUCTION_PORTFOLIO.summary.canonicalQuestionCount,2375);assert.equal(ASSESSMENT_V2_PRODUCTION_PORTFOLIO.summary.humanReviewQueueCount,2370);});
test('altı görevlik Bilişim örneklemi otomatik onay, kişisel veri veya oyun açılışı üretmez',()=>{assert.equal(MIDDLE_SCHOOL_TYMM_COMPUTING_REVIEW_SAMPLE_AUDIT.ok,true,MIDDLE_SCHOOL_TYMM_COMPUTING_REVIEW_SAMPLE_AUDIT.errors.join('\n'));assert.deepEqual(MIDDLE_SCHOOL_TYMM_COMPUTING_REVIEW_SAMPLE_AUDIT.metrics,{engineCount:2,itemCount:6,perEngine:3,approved:0,pending:6});});
